import { ChainType } from '@phoenix-wallet/core';
import { getFullnodeUrl } from '@mysten/sui/client';

export const chainConfigs = [
  {
    id: '1',
    name: 'Ethereum',
    publicRpcUrl: 'https://eth.rpc.blxrbdn.com',
    privateRpcUrl: 'https://eth.rpc.blxrbdn.com',
    explorerUrl: 'https://etherscan.io',
    chainId: 1,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    chainType: ChainType.EVM,
  },
  {
    id: '137',
    name: 'Polygon',
    publicRpcUrl: 'https://polygon-rpc.com',
    privateRpcUrl: 'https://polygon-rpc.com',
    explorerUrl: 'https://polygonscan.com',
    chainId: 137,
    nativeCurrency: { name: 'Polygon', symbol: 'MATIC', decimals: 18 },
    chainType: ChainType.EVM,
  },
  {
    id: '11155111',
    name: 'Sepolia',
    publicRpcUrl: 'https://ethereum-sepolia-rpc.publicnode.com',
    privateRpcUrl: 'https://ethereum-sepolia-rpc.publicnode.com',
    explorerUrl: 'https://sepolia.etherscan.io',
    chainId: 11155111,
    nativeCurrency: { name: 'Sepolia', symbol: 'ETH', decimals: 18 },
    chainType: ChainType.EVM,
  },
  {
    id: '56',
    name: 'BSC',
    publicRpcUrl: 'https://bsc-dataseed.binance.org',
    privateRpcUrl: 'https://bsc-dataseed.binance.org',
    explorerUrl: 'https://bscscan.com',
    chainId: 56,
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
    chainType: ChainType.EVM,
  },
  {
    id: 'solana_devnet',
    name: 'Solana',
    publicRpcUrl: 'https://api.devnet.solana.com',
    privateRpcUrl: 'https://api.devnet.solana.com',
    explorerUrl: 'https://explorer.solana.com',
    chainId: 999999,
    nativeCurrency: { name: 'Solana', symbol: 'SOL', decimals: 9 },
    chainType: ChainType.SOLANA,
  },
  {
    id: 'solana_mainnet_beta',
    name: 'Solana',
    publicRpcUrl: 'https://api.mainnet-beta.solana.com',
    privateRpcUrl: 'https://api.mainnet-beta.solana.com',
    explorerUrl: 'https://explorer.solana.com',
    chainId: 666666,
    nativeCurrency: { name: 'Solana', symbol: 'SOL', decimals: 9 },
    chainType: ChainType.SOLANA,
  },
  // sui mainnet
  {
    id: 'sui:mainnet',
    name: 'Sui',
    publicRpcUrl: getFullnodeUrl('mainnet'),
    privateRpcUrl: getFullnodeUrl('mainnet'),
    explorerUrl: 'https://suiscan.xyz/mainnet',
    chainId: 101,
    nativeCurrency: { name: 'Sui', symbol: 'SUI', decimals: 9 },
    chainType: ChainType.SUI,
  },

  {
    id: 'sui:testnet',
    name: 'Sui',
    publicRpcUrl: getFullnodeUrl('testnet'),
    privateRpcUrl: getFullnodeUrl('testnet'),
    explorerUrl: 'https://suiscan.xyz/testnet',
    chainId: 103,
    nativeCurrency: { name: 'Sui', symbol: 'SUI', decimals: 9 },
    chainType: ChainType.SUI,
  },
  {
    id: 'aptos_mainnet',
    name: 'Aptos',
    publicRpcUrl: 'https://fullnode.mainnet.aptoslabs.com/v1',
    privateRpcUrl: 'https://fullnode.mainnet.aptoslabs.com/v1',
    explorerUrl: 'https://explorer.aptoslabs.com/?network=mainnet',
    chainId: 1,
    nativeCurrency: { name: 'Aptos', symbol: 'APT', decimals: 8 },
    chainType: ChainType.APTOS,
  },
  {
    id: 'aptos_testnet',
    name: 'Aptos',
    publicRpcUrl: 'https://fullnode.testnet.aptoslabs.com/v1',
    privateRpcUrl: 'https://fullnode.testnet.aptoslabs.com/v1',
    explorerUrl: 'https://explorer.aptoslabs.com/?network=testnet',
    chainId: 2,
    nativeCurrency: { name: 'Aptos', symbol: 'APT', decimals: 8 },
    chainType: ChainType.APTOS,
  },
];
